---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.module"
  - "**.py"
exclude_paths:
- test/**/*
- .codeclimate.yml
